AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "API de gesti\xF3n de libros"
Resources:
  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Books
      AttributeDefinitions:
      - AttributeName: bookId
        AttributeType: S
      - AttributeName: genre
        AttributeType: S
      KeySchema:
      - AttributeName: bookId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: GenreIndex
        KeySchema:
        - AttributeName: genre
          KeyType: HASH
        Projection:
          ProjectionType: ALL
  AuthorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Authors
      AttributeDefinitions:
      - AttributeName: authorId
        AttributeType: S
      KeySchema:
      - AttributeName: authorId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  GenresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Genres
      AttributeDefinitions:
      - AttributeName: genreId
        AttributeType: S
      KeySchema:
      - AttributeName: genreId
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: states.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: StepFunctionsInvokeLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - Fn::GetAtt:
              - CheckAuthorFunction
              - Arn
            - Fn::GetAtt:
              - CheckGenresFunction
              - Arn
            - Fn::GetAtt:
              - CreateBookFunction
              - Arn
  CheckGenresFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/checkGenres.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: GenresTable
      CodeUri: CheckGenresFunction
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CheckGenresFunction6ba65b32DepLayer
    Metadata:
      SamResourceId: CheckGenresFunction
  CheckAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/createAuthor.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: AuthorsTable
      CodeUri: CheckAuthorFunction
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CheckAuthorFunctionfc72e75dDepLayer
    Metadata:
      SamResourceId: CheckAuthorFunction
  CreateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/createBook.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books
            Method: post
      CodeUri: CreateBookFunction
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CreateBookFunctione480892fDepLayer
    Metadata:
      SamResourceId: CreateBookFunction
  BookCreationStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::GetAtt:
        - StateMachineExecutionRole
        - Arn
      DefinitionString:
        Fn::Sub: "{\n  \"Comment\": \"Flujo de trabajo para crear un libro\",\n  \"\
          StartAt\": \"CheckAuthor\",\n  \"States\": {\n    \"CheckAuthor\": {\n \
          \     \"Type\": \"Task\",\n      \"Resource\": \"${CheckAuthorFunction.Arn}\"\
          ,\n      \"Next\": \"CheckGenres\"\n    },\n    \"CheckGenres\": {\n   \
          \   \"Type\": \"Task\",\n      \"Resource\": \"${CheckGenresFunction.Arn}\"\
          ,\n      \"Next\": \"CreateBook\"\n    },\n    \"CreateBook\": {\n     \
          \ \"Type\": \"Task\",\n      \"Resource\": \"${CreateBookFunction.Arn }\"\
          ,\n      \"End\": true\n    }\n  }\n}\n"
  GetBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/getBook.handler
      Runtime: nodejs18.x
      CodeUri: GetBookFunction
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books/{bookId}
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetBookFunction9f08143eDepLayer
    Metadata:
      SamResourceId: GetBookFunction
  GetAllBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/listBooks.handler
      Runtime: nodejs18.x
      CodeUri: GetAllBookFunction
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetAllBookFunction0792057eDepLayer
    Metadata:
      SamResourceId: GetAllBookFunction
  UpdateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/updateBook.handler
      Runtime: nodejs18.x
      CodeUri: UpdateBookFunction
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books/{bookId}
            Method: put
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.UpdateBookFunction79658623DepLayer
    Metadata:
      SamResourceId: UpdateBookFunction
  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/deleteBook.handler
      Runtime: nodejs18.x
      CodeUri: DeleteBookFunction
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books/{bookId}
            Method: delete
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.DeleteBookFunction60a79061DepLayer
    Metadata:
      SamResourceId: DeleteBookFunction
  DeleteMultipleBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/book/deleteBooks.handler
      Runtime: nodejs18.x
      CodeUri: DeleteMultipleBookFunction
      Environment:
        Variables:
          BOOKS_TABLE:
            Ref: BooksTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: BooksTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /books
            Method: delete
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.DeleteMultipleBookFunction77cb9187DepLayer
    Metadata:
      SamResourceId: DeleteMultipleBookFunction
  CreateAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/createAuthor.handler
      Runtime: nodejs18.x
      CodeUri: CreateAuthorFunction
      Environment:
        Variables:
          AUTHORS_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: AuthorsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /authors
            Method: post
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CreateAuthorFunctionfe748253DepLayer
    Metadata:
      SamResourceId: CreateAuthorFunction
  GetAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/getAuthor.handler
      Runtime: nodejs18.x
      CodeUri: GetAuthorFunction
      Environment:
        Variables:
          AUTHORS_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: AuthorsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /authors/{authorId}
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetAuthorFunction86709db7DepLayer
    Metadata:
      SamResourceId: GetAuthorFunction
  GetAllAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/listAuthors.handler
      Runtime: nodejs18.x
      CodeUri: GetAllAuthorFunction
      Environment:
        Variables:
          AUTHORS_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: AuthorsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /authors
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetAllAuthorFunctiond77fd901DepLayer
    Metadata:
      SamResourceId: GetAllAuthorFunction
  UpdateAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/updateAuthor.handler
      Runtime: nodejs18.x
      CodeUri: UpdateAuthorFunction
      Environment:
        Variables:
          AUTHORS_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: AuthorsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /authors/{authorId}
            Method: put
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.UpdateAuthorFunction79449371DepLayer
    Metadata:
      SamResourceId: UpdateAuthorFunction
  DeleteAuthorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/author/deleteAuthor.handler
      Runtime: nodejs18.x
      CodeUri: DeleteAuthorFunction
      Environment:
        Variables:
          AUTHORS_TABLE:
            Ref: AuthorsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: AuthorsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /authors/{authorId}
            Method: delete
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.DeleteAuthorFunctionc75e3510DepLayer
    Metadata:
      SamResourceId: DeleteAuthorFunction
  CreateGenreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/createGenre.handler
      Runtime: nodejs18.x
      CodeUri: CreateGenreFunction
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: GenresTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /genres
            Method: post
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.CreateGenreFunctioncc210cbcDepLayer
    Metadata:
      SamResourceId: CreateGenreFunction
  GetGenreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/getGenre.handler
      Runtime: nodejs18.x
      CodeUri: GetGenreFunction
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: GenresTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /genres/{genreId}
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetGenreFunctionb64c0ff3DepLayer
    Metadata:
      SamResourceId: GetGenreFunction
  GetAllGenreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/listGenres.handler
      Runtime: nodejs18.x
      CodeUri: GetAllGenreFunction
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: GenresTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /genres
            Method: get
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.GetAllGenreFunction1449cd64DepLayer
    Metadata:
      SamResourceId: GetAllGenreFunction
  UpdateGenreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/updateGenre.handler
      Runtime: nodejs18.x
      CodeUri: UpdateGenreFunction
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: GenresTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /genres/{genreId}
            Method: put
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.UpdateGenreFunctionf35df6a8DepLayer
    Metadata:
      SamResourceId: UpdateGenreFunction
  DeleteGenreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/genre/deleteGenre.handler
      Runtime: nodejs18.x
      CodeUri: DeleteGenreFunction
      Environment:
        Variables:
          GENRES_TABLE:
            Ref: GenresTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: GenresTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGateway
            Path: /genres/{genreId}
            Method: delete
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.DeleteGenreFunction6c02513aDepLayer
    Metadata:
      SamResourceId: DeleteGenreFunction
  SomeOtherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/someOtherFunction.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          STATE_MACHINE_ARN:
            Fn::ImportValue: StateMachineArn
      CodeUri: SomeOtherFunction
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.SomeOtherFunctionf2e51c33DepLayer
    Metadata:
      SamResourceId: SomeOtherFunction
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: C:\repositoriosgit\Nueva carpeta (2)\PRUEBA-JAN\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  StateMachineArnOutput:
    Value:
      Fn::GetAtt:
      - BookCreationStateMachine
      - Arn
    Description: "ARN de la m\xE1quina de estado"
  ApiGatewayUrl:
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/api/
